<h2>Problem Overview :

1. Goal: Demonstrate Hebbian learning for storing simple binary patterns.

2. Dataset: Custom simple binary patterns (e.g., 3×3 or 4×4 matrices representing letters or shapes).

3. Deliverable: Learned weight matrix and ability to recall stored patterns.

<h3>Why Hebbian Learning?

1. Based on the principle: "Neurons that fire together, wire together."

2. Updates weights based on correlation between input neurons.

3. No backpropagation; simple local learning rule.

<h3>Hebbian Learning Rule

For a network of N neurons:

                   W=p=1∑P​x(p)⋅x(p)T

       x^(p) → input pattern vector
       P → number of patterns
       Weight matrix W is symmetric, with W[i,i] = 0 (no self-connection)
Update / recall:

                     y=sign(W⋅x)
- Output y should reproduce the original pattern x.

In [1]:
import numpy as np

# -----------------------------
# 1️⃣ Define Binary Patterns
# -----------------------------
# Example: 3x3 patterns flattened
patterns = np.array([
    [1, -1, 1,
     -1, 1, -1,
      1, -1, 1],  # Pattern A

    [1, 1, 1,
     -1, -1, -1,
      1, 1, 1]   # Pattern B
])

num_neurons = patterns.shape[1]

# -----------------------------
# 2️⃣ Hebbian Learning
# -----------------------------
W = np.zeros((num_neurons, num_neurons))

for p in patterns:
    W += np.outer(p, p)

# Remove self-connections
np.fill_diagonal(W, 0)

print("✅ Learned Weight Matrix:")
print(W)

# -----------------------------
# 3️⃣ Recall Patterns
# -----------------------------
def recall(input_pattern, W):
    return np.sign(W @ input_pattern)

for idx, p in enumerate(patterns):
    recalled = recall(p, W)
    print(f"\nPattern {idx+1} Original: {p}")
    print(f"Pattern {idx+1} Recalled : {recalled}")


✅ Learned Weight Matrix:
[[ 0.  0.  2. -2.  0. -2.  2.  0.  2.]
 [ 0.  0.  0.  0. -2.  0.  0.  2.  0.]
 [ 2.  0.  0. -2.  0. -2.  2.  0.  2.]
 [-2.  0. -2.  0.  0.  2. -2.  0. -2.]
 [ 0. -2.  0.  0.  0.  0.  0. -2.  0.]
 [-2.  0. -2.  2.  0.  0. -2.  0. -2.]
 [ 2.  0.  2. -2.  0. -2.  0.  0.  2.]
 [ 0.  2.  0.  0. -2.  0.  0.  0.  0.]
 [ 2.  0.  2. -2.  0. -2.  2.  0.  0.]]

Pattern 1 Original: [ 1 -1  1 -1  1 -1  1 -1  1]
Pattern 1 Recalled : [ 1. -1.  1. -1.  1. -1.  1. -1.  1.]

Pattern 2 Original: [ 1  1  1 -1 -1 -1  1  1  1]
Pattern 2 Recalled : [ 1.  1.  1. -1. -1. -1.  1.  1.  1.]


<h2>Notebook Deliverables :

1. Custom binary patterns

2. Learned weight matrix (W)

3. Recall demonstration for stored patterns

4. Observations on perfect recall vs interference